services:
  - type: web
    name: portfolio-priyam-backend
    env: node
    region: oregon
    branch: main
    plan: starter
    root: ./
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: CONTACT_EMAIL
      - key: SMTP_HOST
      - key: SMTP_PORT
      - key: SMTP_SECURE
      - key: SMTP_USER
      - key: SMTP_PASS
